config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sensors#index'

  resources :sensors
  resources :labels
  resources :results

  namespace :api do
    namespace :v1 do
      resources :results
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :sensor
  has_many :results

  validates :title, presence: true,
            length: {minimum: 1}
  validates :group_mode, presence: true
  validates :time_range, presence: true

  validates_inclusion_of :group_mode, :in => :time_selection_values
  validates_inclusion_of :time_range, :in => :time_selection_values

  enum time_mode: [ :period, :current ]

  def current_value
    @result = results_in_time_range.last unless results_in_time_range.nil?
    if @result.present?
      @result.value
    else
      "No data"
    end
  end

  def average_value
    if not results_in_time_range.nil?

      sum = 0

      results_in_time_range.each do |result|
        sum += result.value
      end

      if results_in_time_range.count != 0
        sum / results_in_time_range.count
      else
        "No data"
      end

    else
      "No data"
    end
  end

  def graph_object
    results_by_group_mode
  end

  def results_by_group_mode
    unless results_in_time_range.nil?
      group_by_method = 'group_by_' + self.group_mode
      if self.results.respond_to? group_by_method
        results_in_time_range.public_send(group_by_method, :created_at, "avg", "value")
      else
        results_in_time_range.group(:created_at).average(:value)
      end
    end
  end

  def results_in_time_range
    if self.time_range == 'default' or self.time_range.nil?
      return self.results
    end

    if self.time_mode == 'period'
      if 1.respond_to? self.time_range
        self.results.where(:created_at => 1.public_send(self.time_range).ago..Time.now)
      end
    else
      time_method = 'beginning_of_' + self.time_range
      if Time.now.respond_to? time_method
        self.results.where(:created_at => Time.now.public_send(time_method)..Time.now)
      end
    end
  end

  def time_selection_values
    %w(default second minute hour day week month quarter year)
  end
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :label

  validates :value, presence: true, numericality: true
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  has_many :labels

  validates :title, presence: true,
            length: {minimum: 3}
end

app/controllers/api/v1/results_controller.rb
class Api::V1::ResultsController < ApplicationController
  protect_from_forgery except: :create

  def create
    @label = Label.find(params[:label])

    if @label.results.create(result_params)
      render nothing: true, status: :ok
    else
      render nothing: true, status: :bad_request
    end
  end

  private
    def result_params
      params.require(:result).permit(:value)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  def show
    @label = Label.find(params[:id])
    render 'success'
  end

  def new
    @sensor = Sensor.find(params[:sensor])
    @label = @sensor.labels.new
  end

  def create
    @sensor = Sensor.find(params[:sensor])

    if @sensor.labels.create(label_params)
      @label = @sensor.labels.last
      render 'success'
    else
      render 'new'
    end
  end

  def edit
    @label = Label.find(params[:id])
    @sensor = @label.sensor
  end

  def update
    @label = Label.find(params[:id])
    @sensor = @label.sensor

    if @label.update(label_params)
      redirect_to sensors_path
    else
      render 'edit'
    end
  end

  def destroy
    @label = Label.find(params[:id])
    @label.destroy

    redirect_to sensors_path
  end

  private
    def label_params
      params.require(:label).permit(:title, :group_mode, :time_range, :time_mode)
    end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  protect_from_forgery except: :create

  def new
     @label = Label.new
  end

  def create
    @label = Label.find(params[:label])

    if @label.results.create(result_params)
      redirect_to sensors_path
    end
  end

  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    redirect_to sensors_path
  end

  private
    def result_params
      params.require(:result).permit(:value)
    end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  def index
    @sensors = Sensor.all
  end

  def new
    @sensor = Sensor.new
  end

  def create
    @sensor = Sensor.new(sensor_params)

    if @sensor.save
      redirect_to sensors_path
    else
      render 'new'
    end
  end

  def edit
    @sensor = Sensor.find(params[:id])
  end

  def update
    @sensor = Sensor.find(params[:id])

    if @sensor.update(sensor_params)
      redirect_to sensors_path
    else
      render 'edit'
    end
  end

  def destroy
    @sensor = Sensor.find(params[:id])
    @sensor.destroy

    redirect_to sensors_path
  end

  private
    def sensor_params
      params.require(:sensor).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/labels/_form.erb
<%= form_for @label do |f| %>
    <%= hidden_field_tag('sensor', @sensor.id) %>

    <div class="mdl-card__supporting-text">
      <% if @label.errors.any? %>
          <div id="message message-error">
            <h5>
              <%= pluralize(@label.errors.count, "error") %> occured while saving this label.
            </h5>
            <ul>
              <% @label.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.label :title, class: "mdl-textfield__label" %>
        <%= f.text_field :title, class: "mdl-textfield__input" %>
      </div>

      <div class="mdl-selectfield mdl-js-selectfield">
        <% if @label.time_range.present? %>
          <span>Group results by</span>
        <% end %>
        <%= f.label :group_mode, class: "mdl-selectfield__label" %>
        <%= f.select(:group_mode,
                     @label.time_selection_values,
                     {include_blank: ""},
                     {
                         :class => "mdl-selectfield__select"
                     }
            )
        %>
        <span class="mdl-selectfield__error">Select a value</span>
      </div>

      <div class="mdl-selectfield mdl-js-selectfield mdl-textfield--floating-label">
        <% if @label.time_range.present? %>
          <span>Time range</span>
        <% end %>
        <%= f.label :time_range, class: "mdl-selectfield__label" %>
        <%= f.select(:time_range,
                     @label.time_selection_values,
                     {include_blank: ""},
                     {
                         :class => "mdl-selectfield__select"
                     }
            )
        %>
        <span class="mdl-selectfield__error">Select a value</span>
      </div>

      <p>
        <span>Time Mode</span>
      </p>

      <% Label.time_modes.keys.each do |mode| %>
        <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect">
            <%= f.radio_button :time_mode, mode, class: 'mdl-radio__button' %>
            <span class="mdl-radio__label">
              <%= f.label mode.to_sym %>
            </span>
        </label>
        <br>
      <% end %>
    </div>

    <div class="mdl-card__actions mdl-card--border">
      <%= link_to 'Cancel', sensors_path, :class => 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
      <%= f.submit 'Save', :class => 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
    </div>
<% end %>

app/views/labels/edit.erb
<div class="mdl-card mdl-shadow--6dp" style="margin:auto;">
  <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
    <h2 class="mdl-card__title-text">Edit sensor label</h2>
  </div>
  <%= render 'form' %>
</div>

app/views/labels/new.erb
<div class="mdl-card mdl-shadow--6dp" style="margin:auto;">
  <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
    <h2 class="mdl-card__title-text">Create sensor label</h2>
  </div>
  <%= render 'form' %>
</div>

app/views/labels/success.erb
<div class="mdl-card mdl-shadow--6dp" style="margin:auto;">
  <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
    <h2 class="mdl-card__title-text">Success!</h2>
  </div>
  <div class="mdl-card__supporting-text">
    <p>
      Your label has been created!<br>
      The next step is to feed this label your results.<br>
      You will need to send a POST request to the following endpoint URL:<br>
      <br>
      <span class="mdl-chip">
        <span class="mdl-chip__text">
          <%= api_v1_results_url(:label => @label.id) %>
        </span>
      </span>
      <br>
    <ul class="demo-list-two mdl-list">
        <li class="mdl-list__item mdl-list__item--two-line">
            <span class="mdl-list__item-primary-content">
              <span>result[value]</span>
              <span class="mdl-list__item-sub-title">Type: float</span>
            </span>
        </li>
      </ul>
    </p>
  </div>

  <div class="mdl-card__actions mdl-card--border">
    <%= link_to 'Got it!', sensors_path, :class => 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoomSensor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-color--grey-100">
      <header class="mdl-layout__header mdl-color--primary-dark">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">SensorGraph</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="page-content">
          <div class="mdl-grid">
            <div class="mdl-layout-spacer"></div>
            <div class="mdl-cell mdl-cell--8-col">
              <%= yield %>
            </div>
            <div class="mdl-layout-spacer"></div>
          </div>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/sensors/_form.erb
<%= form_for @sensor do |f| %>
    <div class="mdl-card__supporting-text">
      <% if @sensor.errors.any? %>
          <div id="message message-error">
            <h5>
              <%= pluralize(@sensor.errors.count, "error") %> occured while trying to register this sensor.
            </h5>
            <ul>
              <% @sensor.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.label :title, class: "mdl-textfield__label" %>
        <%= f.text_field :title, class: "mdl-textfield__input" %>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.label :description, class: 'mdl-textfield__label' %>
        <%= f.text_area :description, class: 'mdl-textfield__input' %>
      </div>
    </div>

    <div class="mdl-card__actions mdl-card--border">
      <%= link_to 'Cancel', sensors_path, :class => 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
      <%= f.submit 'Save', :class => 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
    </div>
<% end %>

app/views/sensors/edit.erb
<div class="mdl-card mdl-shadow--6dp" style="margin:auto;">
  <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
    <h2 class="mdl-card__title-text">Edit Sensor</h2>
  </div>
  <%= render 'form' %>

  <%= link_to ('<i class="material-icons">delete</i>').html_safe, sensor_path(@sensor),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: 'mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--4dp mdl-color--accent mdl-floating-button' %>
</div>

app/views/sensors/index.erb
<% @sensors.each do |sensor| %>
    <div class="mdl-card-wide mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
        <h2 class="mdl-card__title-text"><%= sensor.title %></h2>
      </div>
      <div class="mdl-card__supporting-text">
        <%= sensor.description %>
      </div>
      <div class="mdl-card__actions mdl-card__supporting-text mdl-card--border">

        <% sensor.labels.each do |label| %>
            <div class="mdl-card-wide mdl-card mdl-shadow--2dp">
              <div class="mdl-card__title">
                <h2 class="mdl-card__title-text"><%= label.title %></h2>
              </div>
              <div class="mdl-card__supporting-text">

                <div class="mdl-grid">
                  <div class="mdl-cell mdl-cell--3-col">
                    <div class="mdl-card-wide mdl-card  mdl-shadow--2dp mdl-card-compact">
                      <div class="mdl-card__title">
                        <h4 class="mdl-card__title-text">Current <%= label.title %></h4>
                      </div>
                      <div class="mdl-card__supporting-text">
                        <%= label.current_value %>
                      </div>
                    </div>

                    <div class="mdl-card-wide mdl-card  mdl-shadow--2dp mdl-card-compact">
                      <div class="mdl-card__title">
                        <h4 class="mdl-card__title-text">Average <%= label.title %></h4>
                      </div>
                      <div class="mdl-card__supporting-text">
                        <%= number_with_precision label.average_value, :precision => 2 %>
                      </div>
                    </div>
                  </div>
                  <div class="mdl-cell mdl-cell--9-col">
                    <%= area_chart label.graph_object %>
                  </div>
                </div>
              </div>

              <div class="mdl-card__menu">
                <%= link_to ('<i class="material-icons">delete</i>').html_safe,
                            label_path(label),
                            :class => 'mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect',
                            method: :delete,
                            data: {confirm: 'Are you sure?'}
                %>

                <%= link_to ('<i class="material-icons">edit</i>').html_safe,
                            edit_label_path(label),
                            :class => 'mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect'
                %>

                <%= link_to ('<i class="material-icons">info</i>').html_safe,
                            label_path(label),
                            :class => 'mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect'
                %>

              </div>
          </div>
        <% end %>

      </div>

      <div class="mdl-card__actions mdl-card__supporting-text mdl-card--border">
        <%= link_to 'Create label', new_label_path(:sensor => sensor), :class => 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
      </div>


      <div class="mdl-card__menu mdl-color-text--white">
        <%= link_to ('<i class="material-icons">delete</i>').html_safe,
                    sensor_path(sensor),
                    :class => 'mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect',
                    method: :delete,
                    data: {confirm: 'Are you sure?'}
        %>

        <%= link_to ('<i class="material-icons">edit</i>').html_safe,
                    edit_sensor_path(sensor),
                    :class => 'mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect'
        %>
      </div>
    </div>
    <p>&nbsp;</p>
<% end %>

<a href="<%= new_sensor_path %>" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--4dp mdl-color--accent mdl-floating-button">
  <i class="material-icons">add</i>
</a>

app/views/sensors/new.erb
<div class="mdl-card mdl-shadow--6dp" style="margin:auto;">
  <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
    <h2 class="mdl-card__title-text">Add a new Sensor</h2>
  </div>
  <%= render 'form' %>
</div>